### ISSUE TITLE
How to read the results in Table 1?

### ISSUE THREAD

**Issue by hsm207** [zphang/bert_on_stilts#3]
I have some questions about interpreting the results in Table 1.

Here's Table 1 for reference:

![image](https://user-images.githubusercontent.com/2398765/54685552-0b454000-4b52-11e9-8ea5-a146a6fd463f.png)

My questions apply to all models but for simplicity I will just ask about BERT.

My question is:

How to identify the intermediate task for "BERT on STILTS" in the Test Set Scores. For example, in CoLA, the best model in the development set is just BERT with score in 62.1. This is reflected in "BERT, Best of Each". So, in the test set, which model is used for "BERT on STILTS"?

 I'm guessing it has to be the best model within the ones that had intermediate tasks so it's BERT->MNLI since its score is 59.8. So for CoLA, BERT->MNLI scored 59.8 on the development set score and 62.1 in the test set. Is the correct way to read the table?

**Comment by zphang** [comment]
Hi,

It's a good question and I guess we could have written about it more clearly. The best "model" (say, among the BERT models), is chosen based on the development set and shown in the "Best of Each" row. That model is then used on the test set. This spans all intermediate task settings, *including BERT without intermediate training*. Hence, for CoLA we use BERT without additional training, whereas for SST, we use BERT->MNLI.

[This table](https://github.com/zphang/bert_on_stilts#trained-models) also shows which models we end up using. Note that the results there differ slightly because we reran all the experiments (+1 for reproducability!).
